# Generated by Django 2.2 on 2019-04-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('constellation', models.TextField(blank=True)),
                ('birthplace', models.TextField(blank=True)),
                ('occupation', models.TextField(blank=True)),
                ('website', models.TextField(blank=True)),
                ('actor_intro', models.TextField()),
                ('actor_photo', models.ImageField(default='actorset/no_img.jpg', upload_to='actorset/')),
                ('actor_gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('director_date', models.CharField(blank=True, max_length=50, null=True)),
                ('constellation', models.TextField(blank=True)),
                ('birthplace', models.TextField(blank=True)),
                ('occupation', models.TextField(blank=True)),
                ('website', models.TextField(blank=True)),
                ('director_intro', models.TextField()),
                ('director_photo', models.ImageField(default='directorset/no_img.jpg', upload_to='directorset/')),
                ('director_gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('movie_date', models.CharField(blank=True, max_length=50, null=True)),
                ('synopsis', models.TextField()),
                ('type', models.TextField()),
                ('place', models.TextField()),
                ('language', models.TextField()),
                ('length', models.TextField()),
                ('rename', models.TextField()),
                ('movie_photo', models.ImageField(default='movieset/no_img.jpg', upload_to='movieset/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('signature', models.TextField()),
                ('user_photo', models.ImageField(default='userset/no_img.jpg', upload_to='userset/')),
            ],
        ),
        migrations.CreateModel(
            name='Skim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skim_date', models.DateField()),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Movie')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.User')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Actor')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Direct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Director')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('grade', models.IntegerField(blank=True)),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Movie')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.User')),
            ],
        ),
    ]
