# Generated by Django 2.2 on 2019-04-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
