# Generated by Django 2.2 on 2019-04-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190410_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('actor_intro', models.TextField()),
                ('actor_gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('grade', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('director_intro', models.TextField()),
                ('director_gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True)),
                ('synopsis', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('director_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Director')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Actor')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Skim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skim_date', models.DateField()),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('signature', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='skim',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.User'),
        ),
        migrations.AddField(
            model_name='label',
            name='movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.User'),
        ),
    ]
