# Generated by Django 2.2 on 2019-04-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_actor_actor_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='director_date',
        ),
    ]
