# Generated by Django 2.2 on 2019-04-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_director_director_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='director_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
