# Generated by Django 2.2 on 2019-04-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190412_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='photo',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_photo',
            field=models.ImageField(default='actorset/no_img.jpg', upload_to='actorset/'),
        ),
        migrations.AddField(
            model_name='director',
            name='director_photo',
            field=models.ImageField(default='directorset/no_img.jpg', upload_to='directorset/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_photo',
            field=models.ImageField(default='movieset/no_img.jpg', upload_to='movieset/'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(default='userset/no_img.jpg', upload_to='userset/'),
        ),
    ]
