# Generated by Django 2.2 on 2019-04-22 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20190420_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director_name',
        ),
        migrations.CreateModel(
            name='Direct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Director')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Movie')),
            ],
        ),
    ]
