# Generated by Django 2.2 on 2019-04-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_director_director_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_date',
        ),
        migrations.RemoveField(
            model_name='director',
            name='director_date',
        ),
    ]
