# Generated by Django 2.2 on 2019-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190422_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
