# Generated by Django 2.2 on 2019-04-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190422_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date',
            new_name='movie_date',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_date',
            field=models.DateField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='director_date',
            field=models.DateField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
