# Generated by Django 2.2 on 2019-04-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20190422_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_date',
        ),
        migrations.RemoveField(
            model_name='director',
            name='director_date',
        ),
    ]
