# Generated by Django 2.2 on 2019-04-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_remove_movie_movie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
