# Generated by Django 2.2 on 2019-04-23 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_movie_movie_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('birthdate', models.CharField(blank=True, max_length=50, null=True)),
                ('constellation', models.TextField(blank=True, null=True)),
                ('birthplace', models.TextField(blank=True)),
                ('occupation', models.TextField(blank=True)),
                ('website', models.TextField(blank=True)),
                ('intro', models.TextField()),
                ('photo', models.ImageField(default='personset/no_img.jpg', upload_to='personset/')),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='label',
            name='movie_name',
        ),
        migrations.RemoveField(
            model_name='skim',
            name='movie_name',
        ),
        migrations.RemoveField(
            model_name='skim',
            name='user_name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_photo',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='synopsis',
        ),
        migrations.AddField(
            model_name='movie',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direct',
            name='director_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rename',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='actor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Person'),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='Skim',
        ),
    ]
