# Generated by Django 2.2 on 2019-04-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20190423_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='website',
        ),
        migrations.AlterField(
            model_name='person',
            name='birthplace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
